name: ublue akmods 41
on:
  workflow_dispatch:

jobs:
  kernel-akmods:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        fedora_version:
          - 41
        kernel_flavor:
          - main
          - coreos-stable
          - coreos-testing
    with:
      fedora_version: ${{ matrix.fedora_version }}
      kernel_flavor: ${{ matrix.kernel_flavor }}
